#!/usr/bin/env node
/**
 * Stage 1 of the TaskHub -> Cronsole rename: in-repo brand + code identity only.
 *
 * Everything that is *stored*, *external*, or *historical* is protected below.
 * Run with --dry to report without writing.
 */
import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync, statSync } from 'node:fs';
import path from 'node:path';

const DRY = process.argv.includes('--dry');
const root = process.cwd();

// Files never touched by the mechanical pass.
const EXCLUDED_FILES = [
  'docs/CHANGELOG.md',          // historical: records what happened, under the name it happened under
  'docs/ROADMAP.md',            // ditto (the rename item itself lives here)
  'docker-compose.yml',         // Stage 2: container/db/volume names are machine state
  'package-lock.json',          // regenerated from package.json afterwards
];
const EXCLUDED_DIRS = [
  'artifacts/',                 // dated evidence of past runs
  'registry/',                  // generated + content-addressed; regenerated by registry:build
  '.claude/',                   // per-machine tooling, and the skill junction lives here
  'images/',                    // binary
  // The agent's identity is bound to THIS MACHINE: the published exe path, the
  // \Task-Hub\ scheduled task that launches it at logon, and its appsettings
  // beside the binary. Renaming the project here would leave the machine
  // starting a path that no longer exists — an external effect, which is the
  // one thing Stage 1 is defined not to have. It renames with Stage 2.
  'agent/',
];

// Tokens preserved verbatim. Order matters only in that longer ones are listed
// first so a shorter protected token can't shadow them.
const PROTECTED = [
  // --- stored identifiers ---
  'TASKHUB_NATIVE',             // Postgres enum value on every task row
  'taskhub.apiOrigin', 'taskhub.settings', 'taskhub.theme', 'taskhub.token', 'taskhub.user',
  'taskhub.example',            // appears in example config
  // --- machine state (Stage 2) ---
  '\\\\TaskHub',                // "\\TaskHub" in JS/C# string literals
  '\\TaskHub',                  // "\TaskHub" in prose and paths
  'Task-Hub',                   // the agent auto-start scheduler folder
  // Names this machine's Task Scheduler entries and file paths point AT.
  // Renaming them in code without migrating the machine breaks logon start,
  // the self-heal, and the republish helper.
  'TaskHub.Agent', 'TaskHubAgent', 'TaskHubRepublish', 'TaskHubStack',
  'taskhub.ps1', 'Register-TaskHubStack', 'Start-TaskHub',
  'taskhub_test', 'taskhub-backend', 'taskhub-frontend', 'taskhub-db', 'taskhub-redis',
  'postgresql://taskhub', '://taskhub:',
  // --- public surface (Stage 3) ---
  'taskhub-registry', 'taskhub-site', 'taskhub.mikesailab.com', 'michaelschecht/taskhub',
  'mikesailab.com/taskhub',
];

const REPLACEMENTS = [
  [/TaskHub/g, 'Cronsole'],
  [/TASKHUB/g, 'CRONSOLE'],
  [/taskhub/g, 'cronsole'],
  [/Taskhub/g, 'Cronsole'],
];

const tracked = execSync('git ls-files', { encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 })
  .split('\n')
  .map(s => s.trim())
  .filter(Boolean);

const isExcluded = (file) =>
  EXCLUDED_FILES.includes(file) ||
  EXCLUDED_DIRS.some(d => file.startsWith(d)) ||
  file.endsWith('package-lock.json');

const BINARY = /\.(png|jpg|jpeg|gif|ico|svg|woff2?|ttf|eot|zip|msi|exe|dll|pdf)$/i;

let changedFiles = 0;
let changedOccurrences = 0;
const report = [];

for (const file of tracked) {
  if (isExcluded(file) || BINARY.test(file)) continue;

  const abs = path.join(root, file);
  let stat;
  try { stat = statSync(abs); } catch { continue; }
  if (!stat.isFile()) continue;

  const original = readFileSync(abs, 'utf8');
  if (!/taskhub/i.test(original)) continue;

  // Protect, replace, restore.
  let text = original;
  const sentinels = [];
  PROTECTED.forEach((token, i) => {
    if (!text.includes(token)) return;
    const sentinel = `PROT${i}`;
    sentinels.push([sentinel, token]);
    text = text.split(token).join(sentinel);
  });

  let before = text;
  for (const [pattern, to] of REPLACEMENTS) text = text.replace(pattern, to);
  const hits = (before.match(/taskhub/gi) || []).length;

  for (const [sentinel, token] of sentinels) text = text.split(sentinel).join(token);

  if (text !== original) {
    changedFiles++;
    changedOccurrences += hits;
    report.push(`${String(hits).padStart(4)}  ${file}`);
    if (!DRY) writeFileSync(abs, text, 'utf8');
  }
}

console.log(report.sort((a, b) => Number(b.slice(0, 4)) - Number(a.slice(0, 4))).slice(0, 25).join('\n'));
console.log(`\n${DRY ? '[dry run] ' : ''}${changedFiles} files, ${changedOccurrences} occurrences replaced`);
